
{{- if .Values.services.vault.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  url: https://helm.releases.hashicorp.com
  interval: 10m
{{- end }}
