apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-edit
  labels:
    "rbac.skyfjell.io/aggregate-to-platform-edit": "true"
rules:
  - apiGroups:
      - authorizationpolicies.security.istio.io
      - destinationrules.networking.istio.io
      - envoyfilters.networking.istio.io
      - gateways.networking.istio.io
      - istiooperators.install.istio.io
      - peerauthentications.security.istio.io
      - proxyconfigs.networking.istio.io
      - requestauthentications.security.istio.io
      - serviceentries.networking.istio.io
      - sidecars.networking.istio.io
      - telemetries.telemetry.istio.io
      - virtualservices.networking.istio.io
      - wasmplugins.extensions.istio.io
      - workloadentries.networking.istio.io
      - workloadgroups.networking.istio.io
    resources:
      - "*"
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
